#!/usr/bin/env python3
"""Generate panic_symbols_data.c from a GNU ld .map file.

Usage: python3 gen-panic-symbols.py <map_path> <output_path>

Parses every ".text.<name>" section GNU ld emits, keeping only sections
that actually made it into the final image (non-zero address, non-zero
size — a zero address means the linker garbage-collected it,
--gc-sections). Emits a single C source defining a sorted-by-address
panic_symbol_t table plus a deduplicated file-name table, consumed by
firmware/gateway/drivers/cpu/cpu.c via panic_symbol_lookup()
(panic_symbols.h/panic_symbols.c — hand-written, not generated).

Deliberately includes library/kernel symbols (FreeRTOS, mbedTLS,
coreMQTT, libc), not just this project's own code — a real fault hunted
by hand this session was inside FreeRTOS's own xTaskGenericNotify; a
table scoped to "our code only" would have been useless for it.

Two-pass build note: this script needs a .map file to already exist (i.e.
a prior build), and its output needs to be compiled *in* to be useful —
build once, run this, build again. See scripts/regenerate-bringup-certs-usage.txt
for this project's other "external tool, not a CubeIDE build hook"
precedent; this follows the same pattern (manually invoked, or wired into
a CubeIDE External Tool the same way).
"""

import pathlib
import re
import sys

# Matches a ".text.<name>" section header line, optionally with the
# address/size/object-file already on the same line (GNU ld right-pads the
# name column to a fixed width; short names fit inline, long ones don't and
# spill the rest onto the next line instead).
HEADER_RE = re.compile(
    r"^ \.text\.(\S+)"
    r"(?:\s+(0x[0-9a-fA-F]+)\s+(0x[0-9a-fA-F]+)\s+(\S+))?\s*$"
)
# Matches the address/size/object-file line that follows a header-only line.
ADDR_LINE_RE = re.compile(r"^\s+(0x[0-9a-fA-F]+)\s+(0x[0-9a-fA-F]+)\s+(\S+)\s*$")


def parse_map(text):
    """Returns a list of (addr:int, size:int, name:str, objfile:str),
    covering only sections that actually landed in the final image."""
    lines = text.splitlines()
    entries = []
    i = 0
    while i < len(lines):
        m = HEADER_RE.match(lines[i])
        if m is not None:
            name = m.group(1)
            if m.group(2) is not None:
                addr = int(m.group(2), 16)
                size = int(m.group(3), 16)
                objfile = m.group(4)
            else:
                addr = size = None
                objfile = ""
                if (i + 1) < len(lines):
                    m2 = ADDR_LINE_RE.match(lines[i + 1])
                    if m2 is not None:
                        addr = int(m2.group(1), 16)
                        size = int(m2.group(2), 16)
                        objfile = m2.group(3)
            if addr and size:  # both non-zero: real, linked-in code
                entries.append((addr, size, name, objfile))
        i += 1
    return entries


def c_string_literal(s):
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(entries):
    entries = sorted(entries, key=lambda e: e[0])

    files = []
    file_index = {}
    for _, _, _, objfile in entries:
        if objfile not in file_index:
            file_index[objfile] = len(files)
            files.append(objfile)

    lines = []
    lines.append("/**")
    lines.append(" * @file panic_symbols_data.c")
    lines.append(" * @brief GENERATED by scripts/gen-panic-symbols.py -- do not hand-edit.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "panic_symbols.h"')
    lines.append("")
    lines.append("const char *const g_panic_files[] = {")
    for f in files:
        lines.append(f"    {c_string_literal(f)},")
    lines.append("};")
    lines.append("")
    lines.append("const panic_symbol_t g_panic_symbols[] = {")
    for addr, size, name, objfile in entries:
        idx = file_index[objfile]
        lines.append(
            f"    {{0x{addr:08x}u, 0x{size:x}u, {c_string_literal(name)}, {idx}u}},"
        )
    lines.append("};")
    lines.append("")
    lines.append(f"const uint32_t g_panic_symbol_count = {len(entries)}u;")
    lines.append("")
    return "\n".join(lines)


def main(map_path, output_path):
    text = pathlib.Path(map_path).read_text(encoding="utf-8", errors="replace")
    entries = parse_map(text)
    if not entries:
        print(f"[gen-panic-symbols] no .text symbols found in {map_path} -- "
              f"is it a real, built gateway.map?", file=sys.stderr)
        sys.exit(1)

    out_text = render(entries)
    out = pathlib.Path(output_path)
    if out.exists() and out.read_text(encoding="utf-8") == out_text:
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(out_text, encoding="utf-8")
    print(f"[gen-panic-symbols] wrote {output_path}: {len(entries)} symbols",
          file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <gateway.map> <output.c>", file=sys.stderr)
        sys.exit(2)
    main(sys.argv[1], sys.argv[2])
