#!/usr/bin/env bash
# Linux/macOS port of regenerate-bringup-certs.ps1 — same four steps, same
# outputs, so the two stay interchangeable:
#   1. server_ext.cnf gets the new SAN
#   2. server.crt is re-signed against the existing CA + server.key
#      (only the SERVER cert is tied to an IP; CA/client material is
#      identity and never changes when the broker's IP does)
#   3. start-mosquitto-tls.{bat,sh} EXPECTED_IP updated
#   4. firmware/gateway/certs/bringup_certs.h rewritten with the CA /
#      client cert / client key DER arrays, PEMs copied alongside
# Everything this touches is gitignored (private keys). This script has no
# secrets in it and is tracked.
#
# Usage: scripts/regenerate-bringup-certs.sh <broker-ip>
#   e.g. scripts/regenerate-bringup-certs.sh "$(ip -4 -o addr show wlo1 | awk '{print $4}' | cut -d/ -f1)"
set -euo pipefail

BROKER_IP="${1:?usage: $0 <broker-ip>}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BROKER_DIR="$REPO_ROOT/local-test/mosquitto-broker"
CERTS_DIR="$REPO_ROOT/firmware/gateway/certs"

cd "$BROKER_DIR"
printf 'subjectAltName = IP:%s,DNS:localhost,IP:127.0.0.1' "$BROKER_IP" > server_ext.cnf
echo "[1/4] server_ext.cnf updated: SAN = IP:$BROKER_IP,DNS:localhost,IP:127.0.0.1"

openssl req -new -key server.key -out server.csr -subj "/CN=iot-environmental-monitor-broker"
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -out server.crt -days 3650 -extfile server_ext.cnf 2>/dev/null
echo "[2/4] server.crt re-signed against existing CA (unchanged CA + server key)"

for f in start-mosquitto-tls.bat "$REPO_ROOT/scripts/start-mosquitto-tls.sh"; do
    [ -f "$f" ] && sed -i -E "s/^(set |)EXPECTED_IP=.*/\1EXPECTED_IP=$BROKER_IP/" "$f"
done
echo "[3/4] EXPECTED_IP updated to $BROKER_IP in the broker start scripts"

mkdir -p "$CERTS_DIR"
to_c_array() { # <der-file> <array-name>  -> 12 bytes per line, matches the .ps1 layout
    echo "static const uint8_t $2[] = {"
    od -An -v -tx1 -w12 "$1" | sed -E 's/^ *//; s/ +$//; s/([0-9a-f]{2})/0x\1/g; s/ /, /g; s/^/    /; s/$/,/'
    echo "};"
}
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP" "$BROKER_DIR/server.csr"' EXIT
openssl x509 -in ca.crt     -outform DER -out "$TMP/ca.der"
openssl x509 -in client.crt -outform DER -out "$TMP/client.der"
openssl pkey -in client.key -outform DER -out "$TMP/client_key.der"

{
cat <<HDR
/**
 * @file bringup_certs.h
 * @brief AUTO-GENERATED by scripts/regenerate-bringup-certs.sh — DO NOT COMMIT, DO NOT EDIT BY HAND.
 *
 * Generated: $(date '+%Y-%m-%d %H:%M:%S')
 * Broker:    $BROKER_IP:8883
 *
 * DER-encoded CA cert, client cert, and client private key for the local
 * Mosquitto TLS bring-up broker (local-test/mosquitto-broker/). Included
 * by hardware bring-up main_test_*.c files instead of hand-pasted byte
 * arrays. Contains private key material — this whole folder is
 * gitignored.
 *
 * Regenerate whenever the broker machine's Wi-Fi IP changes:
 *   scripts/regenerate-bringup-certs.sh <new-ip>      (Linux/macOS)
 *   .\\scripts\\regenerate-bringup-certs.ps1 -BrokerIp <new-ip>  (Windows)
 */

#ifndef BRINGUP_CERTS_H
#define BRINGUP_CERTS_H

#include <stdint.h>

#define BRINGUP_CERTS_BROKER_ENDPOINT "$BROKER_IP"

HDR
to_c_array "$TMP/ca.der"         s_bringup_ca_cert_der;     echo
to_c_array "$TMP/client.der"     s_bringup_client_cert_der; echo
to_c_array "$TMP/client_key.der" s_bringup_client_key_der; echo
echo "#endif /* BRINGUP_CERTS_H */"
} > "$CERTS_DIR/bringup_certs.h"
echo "[4/4] bringup_certs.h written to $CERTS_DIR/bringup_certs.h"

cp -f ca.crt client.crt client.key "$CERTS_DIR/"
echo
echo "Done. Broker endpoint: $BROKER_IP:8883"
echo "All cert material for firmware is in: $CERTS_DIR"
